spring:
  application:
    name: jpa

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver # Mysql 데이터베이스 드라이버
    username: root
    password: 12345
    url: jdbc:mysql://@localhost:3306/thymeleaf	# db 연결 url

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create      # 앱 시작시 테이블 생성
      naming: # 엔터티와 필드 이름을 있는 그대로 테이블과 컬럼명으로 사용
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'        # sql 쿼리 출력
    properties:
      hibernate:
        format_sql: 'true'    # SQL 쿼리를 읽기 쉽게 포멧팅(정렬)해서 출력하는 설정
        highlight_sql: true   # SQL 하이라이트 (선택사항)
        use_sql_comments: true # SQL 주석 표시 (선택사항)


  messages:
    basename: messages/message    # 메시지 파일 위치
    encoding: UTF-8
    cache-duration: PT1H    # 캐시 시간 (1시간)
    fallback-to-system-locale: false  # 시스템 locale 사용 여부
    always-use-message-format: false    # MessageFormat 항상 사용 여부

server:
  port: 8081

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 파라미터 값 출력
#    org.hibernate.orm.jdbc.bind: TRACE


