package com.initializr.springstarter.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity // JPA 엔티티 클래스 명시 - 데이터베이스 테이블과 매핑
@Table(name= "BOOK")  // 테이블명 명시 (Oracle은 대문자 선호)
@Getter
@Setter
@NoArgsConstructor
public class Book {
    @Id // 해당 필드가 Primary Key임을 명시
    @GeneratedValue(strategy = GenerationType.IDENTITY) // 기본키 생성 전략 : 자동 증가
    @Column(name = "ID")
    private Long id;        // 책의 고유 식별자

    @Column(name = "SUBJECT")
    private String subject;

    @Column(name = "PRICE")
    private int price;

    @Column(name = "AUTHOR")
    private String author;

    @Column(name = "PAGE_COUNT")
    private int page;

    @Column(name = "CREATED_AT")
    private LocalDateTime createdAt;
}


/*
create table book (
        page_count number(10,0),
        price number(10,0),
        created_at timestamp(6),
        id number(19,0) generated by default as identity,
        author varchar2(255 char),
        subject varchar2(255 char),
        primary key (id)
    )
 */